version: "3"

volumes:
  db_profile_data: {}
  prometheus_data: {}
  grafana_data: {}

networks:
  db:
    driver: bridge
  grpc:
    driver: bridge
  http:
    driver: bridge
  monitoring-front:
    driver: bridge
  monitoring-back:
    driver: bridge

services:
  #############
  # Databases #
  #############
  db-profile:
    image: mariadb:10.2
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_SVC_DEVICE_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - db_device_data:/var/lib/mysql
    networks:
      - db


  ############
  # Services #
  ############
  svc-api-gateway:
    image: ${GOMEET_NS}/svc-api-gateway:${TAG_SVC_API_GATEWAY}
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    command: serve --jwt-secret "${JWT_SECRET}" --svc-echo-address "svc-echo:13000" --svc-profile-address "svc-profile:13000"
    ports:
      - 8383:13000
    depends_on:
      - svc-echo
      - svc-profile
    networks:
      - monitoring-back
      - grpc
      - http

  svc-echo:
    image: ${GOMEET_NS}/svc-echo:${TAG_SVC_ECHO}
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    command: serve --jwt-secret "${JWT_SECRET}"
    networks:
      - monitoring-back
      - grpc
      - http

  svc-profile:
    image: ${GOMEET_NS}/svc-profile:${TAG_SVC_PROFILE}
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    command: serve --jwt-secret "${JWT_SECRET}" --mysql-migrate --mysql-dsn "${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(db-profile:3306)/${MYSQL_SVC_PROFILE_DATABASE}"
    networks:
      - monitoring-back
      - grpc
      - http

  ############
  # Consoles #
  ############
  console-api-gateway:
    image: ${GOMEET_NS}/svc-api-gateway:${TAG_SVC_API_GATEWAY}
    command: console --address=svc-api-gateway:13000
    depends_on:
      - svc-api-gateway
    networks:
      - grpc

  console-echo:
    image: ${GOMEET_NS}/svc-echo:${TAG_SVC_ECHO}
    command: console --address=svc-echo:13000
    depends_on:
      - svc-echo
    networks:
      - grpc

  console-profile:
    image: ${GOMEET_NS}/svc-profile:${TAG_SVC_PROFILE}
    command: console --address=svc-profile:13000
    depends_on:
      - svc-profile
    networks:
      - grpc

  #################
  # Extra - Infra #
  #################
  go-swagger:
    # container_name: go-swagger
    image: gomeet/gomeet-go-swagger
    depends_on:
      - svc-api-gateway
    command: [ "serve", "http://svc-api-gateway:13000/api/v1/swagger.json" ]
    environment:
      - PORT=80
    ports:
      - 8000:80
    networks:
      - http

  prometheus:
    image: prom/prometheus:v1.8.2
    # container_name: gomeet-prometheus
    volumes:
      - ../prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      - '-alertmanager.url=http://alertmanager:9093'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - alertmanager
    depends_on:
      - svc-api-gateway
    networks:
      - monitoring-back

  grafana:
    image: grafana/grafana:4.6.2
    # container_name: gomeet-grafana
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    env_file:
      - ../config.monitoring
    networks:
      - monitoring-back
      - monitoring-front

  alertmanager:
    image: prom/alertmanager:v0.10.0
    ports:
      - 9093:9093
    volumes:
      - ../alertmanager/:/etc/alertmanager/
    networks:
      - monitoring-back
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'

  cadvisor:
    image: google/cadvisor:v0.25.0
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      - monitoring-back

  node-exporter:
    # container_name: node-exporter
    image: prom/node-exporter:v0.15.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    expose:
      - 9100
    networks:
      - monitoring-back
