# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'gomeet-svc-api-gateway'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets:
        - "prometheus:9090"
        - "cadvisor:8080"
        - "node-exporter:9100"
        - "svc-api-gateway:13000"
        - "svc-bi:13000"
        - "svc-device:13000"
        - "svc-echo:13000"
        - "svc-legal-log:13000"
        - "svc-moderation:13000"
        - "svc-portfolio:13000"
        - "svc-profile:13000"
        - "svc-user:13000"

  - job_name: 'svc-api-gateway'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-api-gateway:13000"

  - job_name: 'svc-bi'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-bi:13000"
  - job_name: 'svc-device'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-device:13000"
  - job_name: 'svc-echo'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-echo:13000"
  - job_name: 'svc-legal-log'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-legal-log:13000"
  - job_name: 'svc-moderation'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-moderation:13000"
  - job_name: 'svc-portfolio'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-portfolio:13000"
  - job_name: 'svc-profile'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-profile:13000"
  - job_name: 'svc-user'
    scrape_interval: 5s
    static_configs:
      - targets:
        - "svc-user:13000"
